version: 2

builds:
  - binary: npiperelay
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - arm64
      - amd64

archives:
  - id: zip
    formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

changelog:
  sort: asc
